name: CI for macOS, Linux, Windows

on: [push, pull_request]

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-gcc, macos-clang, windows-msvc, ubuntu-clang]
        include:
          - name: windows-msvc
            os: windows-latest
            cxx: cl.exe
            cc: cl.exe
          - name: ubuntu-clang
            os: ubuntu-latest
            cxx: clang++
            cc: clang
          - name: macos-clang
            os: macos-latest
            cxx: clang++
            cc: clang
          - name: ubuntu-gcc
            os: ubuntu-latest
            cxx: g++
            cc: gcc

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest

    - uses: ilammy/msvc-dev-cmd@v1
    
    - uses: lukka/set-shell-env@v1
      with:
        CXX: ${{ matrix.cxx }}
        CC: ${{ matrix.cc }}
    
    - name: configure and build
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/build/'

    - name: regression test (UK based)
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/tests"
        pwd
        ls -l
        ./regressiontest_UK_100th.py

    - name: regression test (US based)
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/tests"
        ./regressiontest_US_based.py

  test-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container_image: ["fedora:latest", "debian:10", "archlinux/base", "ubuntu:bionic", "centos:7", "opensuse/tumbleweed", "alpine:latest"]
    container:
      image: ${{ matrix.container_image }}

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_dependencies.sh

    - name: configure and build
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/build/'

    - name: regression test
      run: |
        cd tests
        pwd
        ls -l
        ./regressiontest_UK_100th.py

    - name: regression test (US based)
      run: |
        cd "${GITHUB_WORKSPACE}/tests"
        ./regressiontest_US_based.py
